kashidasun/config/routes.rb
Kashidasun::Application.routes.draw do
  get "top" => "top#index", as: "top"

  get "userpage" => "userpage#index", as: "userpage"

  get "index" => "index#index", as: "index"

  get "admin" => "admin#index", as: "admin"

  get "delete" => "admin#delete"

  resources :top do
   collection {get "login","logout"}
  end

  resources :userpage do
  end

  resources :index do
    collection {get "ksearch"}
  end

  resources :books do
    collection {get "search"}
  end

  resources :members do
  end


  resources :admin do
    collection {get "member_new" , "member_list"}
    collection {post "member_create"}
    member {delete "book_delete", "member_delete"}
  end

  root to: "top#index"
end

kashidasun/app/controllers/userpage_controller.rb
# coding: utf-8
class UserpageController < ApplicationController

  def index
    @books = Book.where(lending: true).order("lend_date").paginate(page: params[:page], per_page: 5)
    @book2s = Book.where(lending: true).order("lend_date")
    @members = Member.order("id")
    @id=session[:member_id]
    @lend = Member.lending(@id)
    @today = Time.now
    @days = $days
    @flag = false
  end

  def show 
  end

  def new
  end

  def edit
    @member = Member.find(params[:id])
    render layout: "members"
  end

  def create
  end

  def update
    @member = Member.find(params[:id])
    @member.assign_attributes(params[:member])
    if @member.save
      redirect_to @member, notice: "会員情報を更新したよ"
    else
      render "edit",  layout: "index"
    end
  end

  def destroy
  end

end

kashidasun/app/helpers/userpage_helper.rb
module UserpageHelper
end

kashidasun/app/views/userpage/edit.html.erb
<% @page_title="会員情報の編集ページだよ"%>



※ユーザーIDは変更できません
<%= form_for @member,  :url => {:action => 'update'}  do |form| %>
  <%= render "members/user_form", form: form %>
  <%= form.hidden_field :lending %>
  <%= form.hidden_field :admin %>
  <p><%= form.submit "編集" %></p>
<% end %>

<%= form_tag :userpage, method: :get do %>
  <p><%= submit_tag "ユーザーページトップに戻る" %></p>
<% end %>

kashidasun/app/views/userpage/index.html.erb
<% @members.each do |member| %>
  <% if member.member_id == session[:member_id] %>
    <% @member_name = member.name %>
    <% @this_member = member %>
  <% end %>
<% end %>

<% @page_title = @member_name+'さんのユーザーページだよ' %>

<% if @lend %>
  <% @book2s.each do |book| %>
    <% if book.lending && book.member_id == @id && book.lend_date.beginning_of_day.advance(days: @days) < @today %>
      <% @flag = true %>
      <tr>
        <td><font size="5" color="#ff0000">・『<%= book.title %>』</font></td>
      </tr>
      <br>
    <% end %>
  <% end %>
  <% if @flag %>
    <td><font size="5" color="#ff0000">の返却期限が過ぎています！！</font></td>
    <br>
  <% end %>
<% end %>

<p><%= link_to "会員情報の編集ページ", edit_userpage_path(@this_member) %></p>

<br>

<%= form_tag :ksearch_index_index, method: :get do %>
  <p><%= text_field_tag "q", params[:q] %>
  <%= submit_tag "キーワード検索" %></p>
<% end %>

<br>

<p>あなたが今借りている本</p>
<% if @lend %>
  <% @book2s.each do |book| %>
     <% if book.lending && book.member_id == @id %>
       <tr>
         <td><%= book.title %></td>
       </tr>
       <%= button_to "返却", book,:confirm => "ほんまに返すで？", method: :delete %>
       <br>
     <% end %>
  <% end %>
<% else %>
  <p>今は1冊も借りてないよ</p>
<% end %>
