kashidasun/config/routes.rb
Kashidasun::Application.routes.draw do
  get "top" => "top#index", as: "top"

  get "userpage" => "userpage#index", as: "userpage"

  get "index" => "index#index", as: "index"

  get "admin" => "admin#index", as: "admin"

  get "delete" => "admin#delete"

  resources :top do
   collection {get "login","logout"}
  end

  resources :userpage do
  end

  resources :index do
    collection {get "ksearch"}
  end

  resources :books do
    collection {get "search"}
  end

  resources :members do
  end


  resources :admin do
    collection {get "member_new" , "member_list"}
    collection {post "member_create"}
    member {delete "book_delete", "member_delete"}
  end

  root to: "top#index"
end

kashidasun/app/views/admin/delete.html.erb
<% @page_title="本の削除ページだよ"%>

※貸出中の本は削除できません
<% if @books.present? %>
  <table class="list">
    <tr>
      <th>タイトル</th>
      <th>著者</th>
      <th>削除欄</th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <% if !book.lending %>
          <td><%= link_to "削除", book_delete_admin_path(book), confirm: "削除するよ？", method: :delete %></td>
        <% else %>
          <td>削除不可</td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @books %>
<% else %>
  <p>本がないよ</p>
<% end %>

<%= form_tag :admin, method: :get do %>
  <p><%= submit_tag "管理者ページトップに戻る" %></p>
<% end %>

kashidasun/app/views/admin/index.html.erb
<% @members.each do |member| %>
  <% if member.member_id == session[:member_id] %>
    <% @member_name = member.name %>
  <% end %>
<% end %>

<% @page_title = "管理者（"+@member_name+"さん）の管理者ページだよ"%>

<p><%= link_to "本の追加ページ", :new_admin %></p>

<p><%= link_to "本の削除ページ", :delete %></p>

<p><%= link_to "利用者の追加ページ", :member_new_admin_index %></p>

<p><%= link_to "利用者の削除ページ", :member_list_admin_index %></p>

kashidasun/app/views/admin/member_list.html.erb
<% @page_title="利用者の削除ページだよ"%>

※本を借りている利用者と自分は削除できません
<% if @members.present? %>
  <table class="list">
    <tr>
      <th>氏名</th>
      <th>ユーザーID</th>
      <th>利用者状況</th>
      <th>削除欄</th>
    </tr>
    <% @members.each do |member| %>
      <tr>
        <% if member.member_id != session[:member_id] %>
          <td><%= member.name %></td>
        <% else %>
          <td>あなた</td>
        <% end %>
        <td><%= member.member_id %></td>
        <% if member.admin == true %>
          <td>管理者です</td>
        <% else %>
          <td><%= member.lending == true ? "本を借りています" : "本を借りていません" %></td>
        <% end %>
        <% if member.lending == false && member.member_id != session[:member_id] %>
          <td><%= link_to "削除", member_delete_admin_path(member), confirm: "削除するよ？", method: :delete %></td>
        <% else %>
          <td>削除不可</td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @members %>
<% else %>
  <p>利用者と管理者がいないよ</p>
<% end %>

<%= form_tag :admin, method: :get do %>
  <p><%= submit_tag "管理者ページトップに戻る" %></p>
<% end %>

kashidasun/app/views/admin/member_new.html.erb
<% @page_title="利用者の追加ページだよ"%>

<%= form_for @member, url: member_create_admin_index_path(@member) do |form| %>
  <%= render "members/form", form: form %>
  <p><%= form.submit "追加" %></p>
<% end %>

<%= form_tag :admin, method: :get do %>
  <p><%= submit_tag "管理者ページトップに戻る" %></p>
<% end %>

kashidasun/app/views/admin/new.html.erb
<% @page_title="本の追加ページだよ"%>

<%= form_for @book, url: admin_path(@book) do |form| %>
  <%= render "books/form", form: form %>
  <p><%= form.submit "追加" %></p>
<% end %>

<%= form_tag :admin, method: :get do %>
  <p><%= submit_tag "管理者ページトップに戻る" %></p>
<% end %>