kashidasun/config/routes.rb
Kashidasun::Application.routes.draw do
  get "top" => "top#index", as: "top"

  get "userpage" => "userpage#index", as: "userpage"

  get "index" => "index#index", as: "index"

  get "admin" => "admin#index", as: "admin"

  get "delete" => "admin#delete"

  resources :top do
   collection {get "login","logout"}
  end

  resources :userpage do
  end

  resources :index do
    collection {get "ksearch"}
  end

  resources :books do
    collection {get "search"}
  end

  resources :members do
  end


  resources :admin do
    collection {get "member_new" , "member_list"}
    collection {post "member_create"}
    member {delete "book_delete", "member_delete"}
  end

  root to: "top#index"
end

kashidasun/app/controllers/top_controller.rb
# coding: utf-8

class TopController < ApplicationController
  before_filter :do_before
    

  def index
    @bookdayo = Book.order("id")
    @today = Time.now
    @count = Book.newbookcount(@bookdayo,@today)
    @days = $days
  end


  def login
    hantei = Member.hantei(params[:a], params[:b])
    admin_hantei = Member.admin_hantei(params[:a])
    if hantei
      session[:login] = true
      session[:member_id] = params[:a]
      if(admin_hantei)
        session[:admin] = true
        redirect_to "/admin"
      else
        redirect_to "/userpage"
      end
    else
      redirect_to "/top", notice: "パスワードが間違っています"
    end
   rescue
      redirect_to "/top", notice: "ユーザー名が間違っています"
  end

  def logout
    session.delete(:login)
    session.delete(:member_id)
    if(session[:admin])
      session.delete(:admin)
    end
    redirect_to "/top"
  end

  def new
    @member = Member.new()
    render layout: "index"
  end

  def create
    @member = Member.new(params[:member])
    if @member.save
       redirect_to @member, notice: "新規で会員登録したよ"
    else
       render "new",layout: "index"
    end
  end


  private
  def do_before
    @books = Book.where(lending: true).order("lend_date").paginate(page: params[:page], per_page: 5)
  end
end

kashidasun/app/helpers/top_helper.rb
module TopHelper
end

kashidasun/app/views/top/index.html.erb
<% @page_title = 'トップページだよ' %>

<p><%= link_to "新規会員登録", new_top_path %></p>


<%= form_tag :ksearch_index_index, method: :get do %>
  <p><%= text_field_tag "q", params[:q] %>
  <%= submit_tag "キーワード検索" %></p>
<% end %>

<% if @count > 0 %>
  新作本
  <br>
  <% @bookdayo.each do |book| %>
    <% if (@today-book.created_at)/86400 < 3 %>
      『 <%= book.title %> 』
       <br>
    <% end %>
  <% end %>
<% end %>

kashidasun/app/views/top/new.html.erb
<% @page_title = '新規会員登録ページだよ' %>

<%= form_for @member, url: top_path(@member) do |form| %>
  <%= render "members/user_form", form: form %>
  <p><%= form.submit "登録" %></p>
<% end %>

<%= form_tag :top, method: :get do %>
  <p><%= submit_tag "トップページに戻る" %></p>
<% end %>